server:
  port: 5010

spring:
  application:
    name: todo

  devtools:
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: adm
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    show-sql: true

  spring:
    security:
      oauth2:
        client:
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
          registration:
            kakao:
              client-id: ed60e3d4a9a2ae07eb1cc155bedb4c48
              client-secret: Z8IUEIjYoDLeOSu8Iq78kTXvXz696nMe
              client-authentication-method: client_secret_post
              redirect-uri: http://localhost:5010/api/v1/auth/kakao
              authorization-grant-type: authorization_code
              client-name: kakao
              scope:
                - profile_nickname
                - profile_image
                - account_email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

jwt:
  secret: b7ae02f34df8baa55facb887ca8f7fb736edddcc7260337ca3b9960e472a15a0abb92b09d869d2ede7e089de907b8376416063e273275672a38e28e6fb5e23d8

